#!/bin/bash

amixer=/usr/bin/amixer
osd_cat=/usr/bin/osd_cat
# Tried using PCM before, but need to do more work to get that to work.
mixer='Master'

osd=1
osd_font='-adobe-courier-bold-r-normal--*-180-*-*-*-*-*-*'
osd_delay=2
osd_options="-p bottom -A center -o 50 -O 1 -c white -b slider"
osd_options="$osd_options -f $osd_font -d $osd_delay"

volume_step=5
volume=$($amixer sget $mixer | tail -n1 | awk -F'[][]' '{print $2}')
volume=${volume%\%}
volume_new=$volume
muted=0
message=''

case $1 in
  mute)
    if $amixer sset Master toggle | grep -q '\[off\]'; then
      # Volume has been muted
      muted=1
    else
      volume_new=$volume
      volume=0
    fi
    ;;
  +)
    volume_new=$((volume + volume_step))
    if [[ $volume_new -gt 100 ]]; then
      volume_new=100
    fi
    ;;
  -)
    volume_new=$((volume - volume_step))
    if [[ $volume_new -lt 0 ]]; then
      volume_new=0
    fi
    ;;
esac

if [[ "$muted" -eq 1 ]]; then
  message="Volume Muted"
fi

if [[ "$volume" -ne "$volume_new" ]]; then
  $amixer -q sset $mixer "${volume_new}%"
  message="Volume: ${volume_new}%"
fi

if [[ "$osd" -eq 1 && -n "$XAUTHORITY" && -n "$message" ]]; then
  pkill osd_cat &>/dev/null
  $osd_cat $osd_options -T "$message" -P $volume_new &
fi
