#!/bin/bash

channel='Master Playback Volume'
amixer=/usr/bin/amixer

osd=1
osd_cat=/usr/bin/osd_cat
osd_font='-adobe-courier-bold-r-normal--*-180-*-*-*-*-*-*'
osd_delay=2
osd_options="-p bottom -A center -o 50 -O 1 -c white -b slider"
osd_options="$osd_options -f $osd_font -d $osd_delay"

vol_min=0
vol_max=255
vol_step=10
vol_old=$($amixer get PCM |
          grep Right: |
          sed -re 's/^.*Playback\s+([0-9]+).*$/\1/')
vol_new=$vol_old

muted=0
message=''

case $1 in
  mute)
    if $amixer set Master toggle | grep -q '\[off\]'; then
      # Volume has been muted
      muted=1
      message="Volume Muted"
    fi
    ;;
  +)
    vol_new=$(($vol_old + $vol_step))
    if [[ $vol_new -gt $vol_max ]]; then
      vol_new=$vol_max
    fi
    ;;
  -)
    vol_new=$(($vol_old - $vol_step))
    if [[ $vol_new -lt $vol_min ]]; then
      vol_new=$vol_min
    fi
    ;;
esac

vol_pct=$((($vol_new*100)/$vol_max))
if [[ "$muted" -eq 0 ]]; then
  message="Volume: $vol_pct"
fi

if [[ $vol_new -ne $vol_old ]]; then
  $amixer -q set PCM $vol_new
fi

if [[ $osd -eq 1 && ! -z "$XAUTHORITY" ]]; then
  pkill osd_cat
  $osd_cat $osd_options -T "$message" -P $vol_pct &
fi
